export {default as About} from './About'
export {default as Contact} from './Contact'
export {default as Hero} from './Hero'
export {default as NavBar} from './NavBar'
export {default as Project} from './Project'
export {default as TechStack} from './TechStack'